name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install jq tool
        run: |
          ls -larth
        # - name: Install jq tool
        # run: |
        #   sudo apt-get update
        #   sudo apt-get install  curl jq  vboot-utils u-boot-tools vbutil_kernel cgpt mkimage build-essential -y
